-- Mac Classic colorscheme (Neovim Lua port)
-- Original: mac_classic.vim by Drew Neil
-- Ported from kickstart.nvim's lua/custom/plugins/mac-classic.lua
-- Modification: bold 제거 (VS Code 스타일, 상태바 UI 제외)

vim.cmd('highlight clear')
if vim.g.syntax_on then vim.cmd('syntax reset') end
vim.o.background  = 'light'
vim.g.colors_name = 'mac_classic'

local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

-- ===== UI =====
hi('Normal',       { fg = '#000000', bg = '#FFFFFF' })
hi('NormalFloat',  { fg = '#000000', bg = '#FFFFFF' })
hi('FloatBorder',  { fg = '#CFCFCF', bg = '#FFFFFF' })
hi('Cursor',       { fg = '#FFFFFF', bg = '#3C4C72' })
hi('CursorLine',   { bg = '#F0F6FF' })
hi('CursorColumn', { bg = '#F0F6FF' })
hi('Visual',       { bg = '#C6DEFF' })
hi('LineNr',       { fg = '#808080', bg = '#EFEFEF' })
hi('VertSplit',    { fg = '#FFFFFF', bg = '#CFCFCF' })
hi('MatchParen',   { fg = '#1E39F6' })
hi('Pmenu',        { bg = '#EFEFEF' })
hi('PmenuSel',     { bg = '#C6DEFF' })
hi('Directory',    { fg = '#D51015' })
hi('Folded',       { fg = '#0066FF', bg = '#FFFFFF' })
hi('NonText',      { fg = '#DFDFDF', bg = '#FFFFFF' })
hi('SpecialKey',   { fg = '#DFDFDF', bg = '#FFFFFF' })

-- StatusLine
hi('StatusLine',   { fg = '#000000', bg = '#C6DEFF', italic = true })
hi('StatusLineNC', { fg = '#000000', bg = '#EFEFEF' })

-- Search
hi('IncSearch', { bg = '#FFCE77' })
hi('Search',    { bg = '#FFE6BB' })

-- ===== Legacy syntax groups =====
hi('Boolean',       { fg = '#6E79F1' })
hi('Character',     { fg = '#D51015' })
hi('Comment',       { fg = '#0066FF', italic = true })
hi('Conditional',   { fg = '#1E39F6' })
hi('Constant',      { fg = '#D51015' })
hi('Define',        { fg = '#1E39F6' })
hi('ErrorMsg',      { fg = '#FFFFFF', bg = '#990000' })
hi('WarningMsg',    { fg = '#FFFFFF', bg = '#990000' })
hi('Float',         { fg = '#0000A2' })
hi('Function',      { fg = '#0000A2' })
hi('Identifier',    { fg = '#1E39F6' })
hi('Keyword',       { fg = '#1E39F6' })
hi('Label',         { fg = '#007B22' })
hi('Number',        { fg = '#0000A2' })
hi('Operator',      { fg = '#1E39F6' })
hi('PreProc',       { fg = '#1E39F6' })
hi('Special',       { fg = '#000000' })
hi('Statement',     { fg = '#1E39F6' })
hi('StorageClass',  { fg = '#1E39F6' })
hi('String',        { fg = '#007B22' })
hi('Title',         { fg = '#000000' })
hi('Todo',          { fg = '#0066FF', reverse = true, italic = true })
hi('Underlined',    { underline = true })

-- ===== Diff =====
hi('diffAdded',   { fg = '#007B22', bg = '#FFFFFF' })
hi('diffRemoved', { fg = '#D51015', bg = '#FFFFFF' })
hi('diffFile',    { fg = '#6E79F1', bg = '#FFFFFF' })
hi('diffNewFile', { fg = '#6E79F1', bg = '#FFFFFF' })
hi('diffLine',    { fg = '#000000', bg = '#FFFFFF' })
hi('diffAdd',     { fg = '#007B22', bg = '#FFFFFF' })
hi('diffChange',  { fg = '#007B22', bg = '#FFFFFF' })
hi('diffText',    { fg = '#007B22', bg = '#FFFFFF' })
hi('diffDelete',  { link = 'diffRemoved' })

-- ===== Git commit =====
hi('gitcommitFirstLine',     { fg = '#000000', bg = '#FFFFFF' })
hi('gitcommitSelectedType',  { fg = '#007B22', bg = '#FFFFFF' })
hi('gitcommitSelectedFile',  { link = 'gitcommitSelectedType' })
hi('gitcommitDiscardedType', { fg = '#D51015', bg = '#FFFFFF' })
hi('gitcommitDiscardedFile', { link = 'gitcommitDiscardedType' })
hi('gitcommitUntrackedFile', { fg = '#6E79F1', bg = '#FFFFFF' })

-- ===== Ruby =====
hi('rubyClass',                   { fg = '#1E39F6' })
hi('rubyFunction',                { fg = '#0000A2' })
hi('rubyInterpolationDelimiter',  { fg = '#00BC41' })
hi('rubyInterpolation',           { fg = '#00BC41' })
hi('rubySymbol',                  { fg = '#D51015' })
hi('rubyConstant',                { fg = '#6E79F1' })
hi('rubyStringDelimiter',         { fg = '#007B22' })
hi('rubyInstanceVariable',        { fg = '#318495' })
hi('rubyInclude',                 { fg = '#1E39F6' })
hi('rubyGlobalVariable',          { fg = '#318495' })
hi('rubyRegexp',                  { fg = '#E18AC7' })
hi('rubyRegexpAnchor',            { fg = '#E18AC7' })
hi('rubyRegexpQuantifier',        { fg = '#E18AC7' })
hi('rubyRegexpParens',            { fg = '#E18AC7' })
hi('rubyRegexpEscape',            { fg = '#00BC41' })
hi('rubyRegexpCharClass',         { fg = '#00BC41' })
hi('rubyRegexpDelimiter',         { fg = '#E18AC7' })
hi('rubyEscape',                  { fg = '#00BC41' })
hi('rubyControl',                 { fg = '#1E39F6' })
hi('rubyOperator',                { fg = '#1E39F6' })
hi('rubyException',               { fg = '#1E39F6' })
hi('rubyPseudoVariable',          { fg = '#318495' })
hi('rubyRailsUserClass',          { fg = '#6E79F1' })
hi('rubyRailsARAssociationMethod',{ fg = '#3C4C72' })
hi('rubyRailsARMethod',           { fg = '#3C4C72' })
hi('rubyRailsRenderMethod',       { fg = '#3C4C72' })
hi('rubyRailsMethod',             { fg = '#3C4C72' })
hi('erubyComment',                { link = 'Comment' })
hi('erubyRailsMethod',            { fg = '#3C4C72' })

-- ===== XML / HTML =====
hi('xmlEndTag',       { link = 'xmlTag' })
hi('htmlTag',         { fg = '#1E39F6' })
hi('htmlEndTag',      { link = 'htmlTag' })
hi('htmlTagName',     { link = 'htmlTag' })
hi('htmlArg',         { link = 'htmlTag' })
hi('htmlSpecialChar', { fg = '#D51015' })
hi('htmlH1',          {})
hi('htmlH2',          { link = 'htmlH1' })
hi('htmlH3',          { link = 'htmlH1' })
hi('htmlH4',          { link = 'htmlH1' })
hi('htmlH5',          { link = 'htmlH1' })
hi('htmlH6',          { link = 'htmlH1' })

-- ===== JavaScript =====
hi('javaScriptFunction',       { fg = '#1E39F6' })
hi('javaScriptFuncName',       { fg = '#318495', italic = true })
hi('javaScriptLabel',          { fg = '#0000A2' })
hi('javaScriptRailsFunction',  { fg = '#3C4C72' })
hi('javaScriptType',           { fg = '#318495' })
hi('javaScriptArgument',       { fg = '#318495', italic = true })
hi('javaScriptRegexpString',   { fg = '#E18AC7' })
hi('javaScriptSpecial',        { fg = '#00BC41' })

-- ===== YAML =====
hi('yamlAnchor',         { fg = '#318495' })
hi('yamlAlias',          { fg = '#318495' })
hi('yamlDocumentHeader', { bg = '#F2F2F2' })

-- ===== CSS =====
hi('cssTagName',                {})
hi('cssIdentifier',             { italic = true })
hi('cssClassName',              { link = 'cssIdentifier' })
hi('cssDefinition',             { fg = '#6E79F1' })
hi('cssRenderProp',             { link = 'cssDefinition' })
hi('cssTextProp',               { link = 'cssDefinition' })
hi('cssFontProp',               { link = 'cssDefinition' })
hi('cssColorProp',              { link = 'cssDefinition' })
hi('cssBoxProp',                { link = 'cssDefinition' })
hi('cssGeneratedContentProp',   { link = 'cssDefinition' })
hi('cssUIProp',                 { link = 'cssDefinition' })
hi('cssCommonAttr',             { fg = '#00BC41' })
hi('cssAttr',                   { link = 'cssCommonAttr' })
hi('cssRenderAttr',             { link = 'cssCommonAttr' })
hi('cssTextAttr',               { link = 'cssCommonAttr' })
hi('cssFontAttr',               { link = 'cssCommonAttr' })
hi('cssGeneratedContentAttr',   { link = 'cssCommonAttr' })
hi('cssURL',                    { fg = '#007B22' })
hi('cssFunctionName',           { fg = '#3C4C72' })
hi('cssColor',                  { fg = '#D51015' })
hi('cssValueLength',            { fg = '#0000A2' })
hi('cssImportant',              { fg = '#1E39F6' })

-- ===== Vimscript =====
hi('vimGroup',        { fg = '#007B22' })
hi('vimHiGroup',      { link = 'vimGroup' })
hi('vimCommentTitle', { fg = '#3C4C72' })
hi('helpSpecial',     { fg = '#6E79F1' })

-- ===== Markdown =====
hi('markdownBold',      { bold = true })  -- 의미상 bold (markdown **굵게** 문법)
hi('markdownItalic',    { italic = true })
hi('markdownCode',      { fg = '#007B22' })
hi('markdownCodeBlock', { link = 'markdownCode' })

-- ===== Treesitter =====
hi('@variable',         { fg = '#000000' })
hi('@variable.builtin', { fg = '#318495' })
hi('@constant',         { fg = '#D51015' })
hi('@constant.builtin', { fg = '#6E79F1' })
hi('@function',         { fg = '#0000A2' })
hi('@function.builtin', { fg = '#0000A2' })
hi('@function.call',    { fg = '#0000A2' })
hi('@method',           { fg = '#0000A2' })
hi('@method.call',      { fg = '#0000A2' })
hi('@keyword',          { fg = '#1E39F6' })
hi('@keyword.function', { fg = '#1E39F6' })
hi('@keyword.return',   { fg = '#1E39F6' })
hi('@keyword.operator', { fg = '#1E39F6' })
hi('@conditional',      { fg = '#1E39F6' })
hi('@repeat',           { fg = '#1E39F6' })
hi('@string',           { fg = '#007B22' })
hi('@string.escape',    { fg = '#00BC41' })
hi('@string.regex',     { fg = '#E18AC7' })
hi('@number',           { fg = '#0000A2' })
hi('@boolean',          { fg = '#6E79F1' })
hi('@type',             { fg = '#6E79F1' })
hi('@type.builtin',     { fg = '#6E79F1' })
hi('@parameter',        { fg = '#318495' })
hi('@property',         { fg = '#318495' })
hi('@field',            { fg = '#318495' })
hi('@comment',          { fg = '#0066FF', italic = true })
hi('@punctuation',      { fg = '#000000' })
hi('@operator',         { fg = '#1E39F6' })
hi('@tag',              { fg = '#1E39F6' })
hi('@tag.attribute',    { fg = '#1E39F6' })
hi('@tag.delimiter',    { fg = '#1E39F6' })

-- ===== LSP semantic tokens =====
hi('@lsp.type.class',     { fg = '#6E79F1' })
hi('@lsp.type.function',  { fg = '#0000A2' })
hi('@lsp.type.method',    { fg = '#0000A2' })
hi('@lsp.type.parameter', { fg = '#318495' })
hi('@lsp.type.property',  { fg = '#318495' })
hi('@lsp.type.variable',  { fg = '#000000' })

-- ===== Diagnostics =====
hi('DiagnosticError',          { fg = '#990000' })
hi('DiagnosticWarn',           { fg = '#D51015' })
hi('DiagnosticInfo',           { fg = '#0066FF' })
hi('DiagnosticHint',           { fg = '#318495' })
hi('DiagnosticUnderlineError', { undercurl = true, sp = '#990000' })
hi('DiagnosticUnderlineWarn',  { undercurl = true, sp = '#D51015' })
hi('DiagnosticUnderlineInfo',  { undercurl = true, sp = '#0066FF' })
hi('DiagnosticUnderlineHint',  { undercurl = true, sp = '#318495' })

-- ===== Telescope (kickstart에 있던 항목, 우리는 fff.nvim 쓰지만 호환용) =====
hi('TelescopeNormal',    { fg = '#000000', bg = '#FFFFFF' })
hi('TelescopeBorder',    { fg = '#CFCFCF', bg = '#FFFFFF' })
hi('TelescopeSelection', { bg = '#C6DEFF' })
hi('TelescopeMatching',  { fg = '#D51015' })

-- ===== WhichKey =====
hi('WhichKey',          { fg = '#1E39F6' })
hi('WhichKeyGroup',     { fg = '#0066FF' })
hi('WhichKeyDesc',      { fg = '#000000' })
hi('WhichKeySeparator', { fg = '#808080' })

-- ===== GitSigns =====
hi('GitSignsAdd',    { fg = '#007B22' })
hi('GitSignsChange', { fg = '#0066FF' })
hi('GitSignsDelete', { fg = '#D51015' })

-- ===== Mini.statusline (UI chrome — bold 유지) =====
hi('MiniStatuslineModeNormal',  { fg = '#FFFFFF', bg = '#3C4C72', bold = true })
hi('MiniStatuslineModeInsert',  { fg = '#FFFFFF', bg = '#007B22', bold = true })
hi('MiniStatuslineModeVisual',  { fg = '#FFFFFF', bg = '#6E79F1', bold = true })
hi('MiniStatuslineModeReplace', { fg = '#FFFFFF', bg = '#D51015', bold = true })
hi('MiniStatuslineModeCommand', { fg = '#FFFFFF', bg = '#0000A2', bold = true })
hi('MiniStatuslineFilename',    { fg = '#000000', bg = '#EFEFEF' })
hi('MiniStatuslineFileinfo',    { fg = '#000000', bg = '#EFEFEF' })
hi('MiniStatuslineDevinfo',     { fg = '#000000', bg = '#C6DEFF' })
